"""
Django settings for blockchain_docs project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from web3 import Web3, HTTPProvider

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '87f+iq1b&%^@cv_w^t1)&jc=_7k=(npk(iaqh%m6!j9ujexmr!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blockchain_docs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blockchain_docs.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
os.environ['WEB3_INFURA_PROJECT_ID'] = '2a66c76e59294895a68c9739378b720c'
os.environ['WEB3_INFURA_PROJECT_SECRET'] = 'f403e4dd14494c04a8b3e59e1b6765a9'
w3 = Web3(HTTPProvider('https://ropsten.infura.io/v3/2a66c76e59294895a68c9739378b720c'))
ABI = [{"inputs": [], "payable": False, "stateMutability": "nonpayable", "type": "constructor"},
       {"constant": False, "inputs": [{"internalType": "string", "name": "newmessage", "type": "string"}],
        "name": "AddMessage", "outputs": [], "payable": True, "stateMutability": "payable", "type": "function"},
       {"constant": True, "inputs": [], "name": "getAll",
        "outputs": [{"internalType": "string[]", "name": "", "type": "string[]"}], "payable": False,
        "stateMutability": "view", "type": "function"},
       {"constant": True, "inputs": [{"internalType": "uint32", "name": "number", "type": "uint32"}],
        "name": "getMessage", "outputs": [{"internalType": "string", "name": "", "type": "string"}], "payable": False,
        "stateMutability": "view", "type": "function"}]
main_contract = w3.eth.contract(
    address="0x34eD0eae736759F6711DcfEdE9a3f56Adfd9A659",
    abi=ABI
)
w3.eth.account = '0xB0329a4B11143e2f57F0238805E05dd96DD1eC5A'
CloseWalletKey = "346F49626F65F952B52CEF5678F9B4AD1DD2B065226CB49579B06F67065789D6"
